### PR TITLE
Display information if summary is not available

### PR DESCRIPTION
**Pull request by elenatorro**
Related issue: https://github.com/CartoDB/cartoframes/issues/1208

### CODE REVIEW

**Comment by Jesus89** [comment]
It would be nice to add some unit tests if possible

**Comment by elenatorro** [comment]
I think we can't use `hasattr` cause afaik this does not work for dicts, I've checked it and it returns false when the `data` has a `summary_json`. I think that it's better to use the `self.data.get('summary_jon')` to avoid the exception instead.

**Comment by elenatorro** [comment]
Done ✅ 

However, I'd add more specific tests for `head`, `tail`, `count` and `fields_by_type`  methods, what do you think? Should we do this in this PR?

**Comment by Jesus89** [comment]
Cool. I think is relatively fast to add unit tests for these 4 methods. If you see that it does not take more than 10 min I would add these tests in the PR. (So we keep improving the coverage little by little)

**Pull request merged**
