### PR TITLE
More examples

### PR DESCRIPTION
**Pull request by michellemho**
This PR adds two new Demo notebooks on how to use CARTOframes with Citibike and earthquake datasets.

To do:
- [ ] update buffer method
- [ ] update DO augmentation method
- [x] remove API key
- [ ] make a more data-sciency example :)

### CODE REVIEW

**Comment by andy-esch** [comment]
How's it going @michellemho?

**Comment by michellemho** [comment]
It's going well, @andy-esch. The examples should be good-to-go; but I would just check to make sure the data augmentation methods still work, since you've made changes. I don't think we've added a new buffering (areas of influence) method; so we can ignore that to-do for now. And finally, I still need to make a more "data science-y" example...

**Comment by andy-esch** [comment]
Hey @michellemho, what's the state of these two notebook?

**Comment by andy-esch** [comment]
Cartoframes times out after 10-25 seconds or so, so I'm not surprised there's an error there. How many geometries are there in that table?

**Comment by elenatorro** [comment]
Closing this PR since it is an old example, feel free to reopen it if necessary :)

**Pull request closed without merging**
