### PR TITLE
Do e2e tests

### PR DESCRIPTION
**Pull request by oleurud**
Solves https://github.com/CartoDB/cartoframes/issues/1365

In order to run them: `pytest tests/e2e/data/observatory`

### CODE REVIEW

**Comment by alasarr** [comment]
Looks good to me too

**Comment by oleurud** [comment]
For the acceptance, I am going to run these new tests in Travis once.

**Comment by oleurud** [comment]
Acceptance :green_apple:

**Comment by oleurud** [comment]
@Jesus89 you skipped some e2e tests https://github.com/CartoDB/cartoframes/pull/1408/commits/6c5b753798817d6a59c16cd56b753d7e6adfbb5a, so, do you want to include e2e tests in Travis again?

**Comment by Jesus89** [comment]
Now the command `pytest tests/e2e/` works because it only runs the e2e/do tests. IMO I would not add these tests in CI, because it requires credentials in the repo and taking into account the number of tests (pr + push) and the Python versions (3.5, 3.6, 3.7 and 3.8) it would run 8 times per commit. Since these tests cost money I would run them manually when required.

**Comment by rafatower** [comment]
As we're moving to GH actions, tests can be executed on specific folders, with private credentials, triggered only on PR's to specific branches (say master or release), etc.

They can save a good amount of manual testing to ensure quality and avoid regressions. Protect your investment... or don't spend time writing them.

My 2 cents :man_shrugging:

**Comment by oleurud** [comment]
Yes, I totally agree about that. I would add it is important to keep updated to know if we are breaking thinks... I know we are doing an effort testing manually every release and it would help

**Pull request merged**
