### PR TITLE
Widgets Documentation

### PR DESCRIPTION
**Pull request by elenatorro**
- Widget Examples [WIP] (@makella & @elenatorro) 
    - Examples notebook
        - [x] default
        - [x] formula
        - [x] category
        - [x] histogram
        - [x] animation
        - [x] time-series
    - Advanced
        - [x] Weather Time Series (@makella 💥) 
- [x] [Guide](http://cartoframes-widgets-doc.developers.carto-staging.com/developers/cartoframes/guides) (@makella & @elenatorro)
- [x] [Read The Docs](https://cartoframes.readthedocs.io/en/documentation-widgets/cartoframes.viz.widgets.html) (@andy-esch  & @elenatorro)

### CODE REVIEW

**Comment by makella** [comment]
thanks @elenatorro!! will get all the pieces of the doc together today on this PR!

**Comment by makella** [comment]
hiii @elenatorro I went through and added more to the widget doc. I also changed the data so we can reuse the same dataset throughout the ntoebook. I have a couple of questions for you about the histogram widget and also want to talk about the animation section before going too far with it. What I'm thinking for this basic notebook, is to only add the animation and time-series widget examples and save the more advanced capabilities for the guide and/or have a second notebook that goes into more details about animation and widgets.

I also added the temperature example to the advanced section. I haven't written any text yet (not sure if we need it) but it is there for us to review also.

**Comment by makella** [comment]
hiiii @elenatorro 

So I completed the widget notebook but a couple of notes based on our conversation this morning:

- I didn't have a chance to move the notebook to the widgets folder, but for now, I think we can keep it as is (in visualization) and tackle with next cycle's doc revamp work
- I kept in the combining widgets and animation and style property sections in this same notebook but reworked it a bit. Basically, there is a section "Taking it Further" that covers combining widgets and animation and style properties (plus the other example of combining an animation and category widget)

It would be great if you could do a quick read through to make sure I didn't miss/mess up anything!

Also, as a note,
- in the animation and time series widget sections, I didn't add the part about adding a widget with a numeric/date field without the filter... I'm not sure if you think we should add that, but something to note for doc updates

**Comment by oleurud** [comment]
The docs are really cool with nice examples, even a backender can understand them

**Pull request merged**
