### PR TITLE
Helper method updates

### PR DESCRIPTION
**Pull request by makella**
- Add classification method (bins helpers)
- Add breaks and buckets (bins helpers)
- Add `description` and `footer` to all helpers
- Update docs and tests
- Fix formatValue for 0

### CODE REVIEW

**Comment by makella** [comment]
this is a PR to expose additional parameters for helper methods:
- for color_bins and size_bins, it adds a `method` parameter to use an alternative classification method (eqintervals or stdeviation)
- for all helper methods, exposes `description` and `footer` parameters for the legend

**Comment by andy-esch** [comment]
For `method` options, could we simplify the inputs to something like:
* `quantiles`
* `equal`
* `stddev` 
* others?

This way it's easier for the user to fill in the data and we could create a mapping from these simpler inputs to that CARTO VL expects.

**Comment by Jesus89** [comment]
Yeah, we can have an internal map for the classification methods.

**Comment by makella** [comment]
@Jesus89 

- added the descriptions for new parameters to each helper
- updated helper notebook with new parameters

**Pull request merged**
