### PR TITLE
Documentation update and ValueError removal

### PR DESCRIPTION
**Pull request by javitonino**
Hey @andy-esch 

I was playing around with cartoframes, and I found a couple of issues. Here is a PR to fix them:
- The documentation regarding ramp styling was out of date (I assume). It was referring to ramps by name, but now they are set as a dictionary (that can be generated from a function). I updated the docs.
- There was an `except` for an instantiated exception, which does not seem to work. It was throwing a confusing error when authentication fails. After this change, the error is a bit better (the response from the server)

Hope it helps, even if it is only a bit :)

### CODE REVIEW

**Comment by andy-esch** [comment]
Hey @javitonino ! For the Documentation piece, I'm going to move it so that color is like in the documentation, not the other way around. The docs are ahead of the code, sorry 😅.

That is, we are going to move it to this simpler form:

```
color={'name': 'colname', 'schema': 'TealRose', 'bins': 5, 'bin_method': 'equal'}
```

**Comment by andy-esch** [comment]
For the auth, fix, I'm not sure why the named map isn't authenticating... There seems to be a larger problem going on here. The reason that exception was caught is:

1. Try to make named map
2. If it fails, it was assumed that it was because a map of that named already exists, so it's ok to fail
3. Move on

I think we need to catch the auth error, but allow the 'already exists' error to pass still.

**Comment by javitonino** [comment]
@andy-esch Ok about the docs 😆 

About the exception, I was playing around configuring cartoframes to use the local instance, and that is what caused the error. In this case, it was an authentication error but the error triggered parsing the source code. Best options I know are:
- Create exception subclasses for internal use, and catch those
- Catch all RuntimeException and then parse the exception message to see if it is a duplicated template error

**Comment by andy-esch** [comment]
closing as these changes were handled in separate PRs. Thanks for flagging them @javitonino :)

**Pull request closed without merging**
