### PR TITLE
[Guide] Visualize Your Data

### PR DESCRIPTION
**Pull request by makella**
added sample notebook:

Notebook: examples/visualization_layers/visualize_your_data.ipynb

This is the basic structure:
- Add Layer
- Add widgets to explore attributes
- Add popups to narrow down which stores are highest/lowest performing stores
- Add additional Layers
- Symbolize with visualization layer helpers and customize
- Set viewport and Basemap
- Create Layout to compare demographics between lowest/highest performing stores

NOTES:
- The choropleth layer I have in there will be switched out with the isochrone layer. spoke with @cesar so we could add more interesting demographic information to be able to show, through a Layout, some different characteristics that could be impacting a stores performance
- The Layout step is broken (still working on it)

### CODE REVIEW

**Comment by makella** [comment]
@alasarr here is v2 (different notebook than the one above):
examples/visualization_layers/visualize_your_data_v2.ipynb

still need to finish the last Layout part and take a look tomorrow morning at the whole thing again tomorrow with fresh eyes. I started outlining some of the story in the notebook just to keep notes as I was going, obviously that will need to get written better outside of the notebook. 

@cmongut wanted to ask you some questions too so will reach out to you tomorrow

thanks!

**Comment by makella** [comment]
@alasarr i think you were looking at my v1 notebook :/ but its ok the story and workflow is pretty much the same. i haven't updated my latest with changes from today, but if you want to take a quick look at the version i'm working on it is: examples/visualization_layers/visualize_your_data_v2.ipynb **v2** sorry about that

regarding that issue, yes! i added a ticket yesterday:
https://github.com/CartoDB/cartoframes/issues/1254

thanks!

**Comment by makella** [comment]
@elenatorro here is my guide...

some notes:
- I changed the title of the guide to "Explore and Visualize Data" so it was more in alignment with the content
- In the guide, I use a Pandas DataFrame for the workflow without the cartoframes credentials/account you can find that workflow in this notebook in case something needs to be updated
  - examples/visualization_layers/visualize_your_data_guide_workflow.ipynb
  - NOTE: in this notebook, the last Layout map isn't working I didn't troubleshoot further since I took a screenshot and @alrocar mentioned it being a JS bundle that may have not been installed on my end properly (?) regardless, it does work in the other notebook below
- The published maps can be found in another notebook that uses the credentials
  - examples/visualization_layers/visualize_your_data_guide_published_maps.ipynb
- I got the tables in from the exported html, hopefully they came out ok!

Other:
- I'm sure I missed some links and/or maybe didn't link the right reference/examples... do you mind checking for me?
- Obviously I haven't previewed this in the Dev Center so I'm not sure what all the content looks like together. I trust your judgement on anything that needs to be formatted differently to look better there

I'm sure there is a lot more but it is late and I am cross eyed! haha... I will have to review once published next week after the holidays.

thanks for taking the time to review it....

**Comment by elenatorro** [comment]
Awesome work, @makella! I just fixed a tiny thing related with an unclosed `<div>`tag, but the rest was perfect ✨ 

I've published the layout visualization as a kuviz so we can embed it as well and it looks great 👍

**Pull request merged**
