### PR TITLE
PostgreSQL date type is read as object type

### PR DESCRIPTION
**Pull request by michellemho**
Offering a fix to the out of bounds datetime issue. Out of bounds timestamps are pulled into the Pandas dataframe as an object (string) type. 

closes https://github.com/CartoDB/cartoframes/issues/66

### CODE REVIEW

**Comment by andy-esch** [comment]
Nice one @michellemho! I how concise it is. @mehak-sachdeva, could you test this?

**Comment by mehak-sachdeva** [comment]
@michellemho @andy-esch 
Great work! I was trying it on my end and I realized an invalid timestamp took up the default '1752-08-29 22:43:41.128654848` in pandas. I am wondering if that is the expected behavior?
The original value of that row in my carto table was '-1-01-01T00:00:00Z'. I am guessing it should have turned it into a string object and made all these values as Null maybe?
Sorry if I am understanding something wrong and let me know if I can help to collaborate?
Thanks!

**Comment by michellemho** [comment]
@mehak-sachdeva, the intended effect in the case that a PostgreSQL date can't be converted to a Pandas date is to turn the value into a string object. It does not turn it into a null value such as NaN or NaT. However, for some reason, your date value has an extra dash in front. This may be causing Pandas to read it as a valid (and strange) timestamp.

The conversion from PostgreSQL dates to Pandas dates seems complicated... it might be easier for Cartoframes to import all PostgreSQL dates as an "object" (string) type instead of attempting a conversion to prevent strange behavior like you found!

**Comment by andy-esch** [comment]
I like the idea of not worrying about converting the postgres datetimes to pandas datetimes. I think that there should be some transparency there to the user that those columns are not converted, though. We could think about adding a named argument for coercing datetimes in there instead ;)

**Comment by michellemho** [comment]
Changed so that PSQL date types are read into Pandas as "object". This solution is to avoid any strange conversion behavior as described above.

**Pull request merged**
