### PR TITLE
Update Style API

### PR DESCRIPTION
**Pull request by elenatorro**
Related issue https://github.com/CartoDB/cartoframes/issues/1345

### CODE REVIEW

**Comment by elenatorro** [comment]
Ready for review @makella && @Jesus89! As we've discussed, there're a couple of things we need to finish related with this task:

> Examples

- [ ] Review and update related examples
- [ ] Review `examples.json` to check which examples we want to include

> About "color" label issue

It's an Airship issue, and I'll solve it there 👍 

> layer helpers

I'll tackle that next after this PR is merged

> documentation (in general)

Let's review it when changing all the `CartoDataFrame` related stuff as well, we'll probably need to coordinate us then

**Comment by makella** [comment]
hi @elenatorro thanks so much!! 

today i am going to do what we discussed and go through all the changes to do testing and make sure that all of our cases are covered - i will also share the notebook i make. 

my next priority will be the examples section (review and `examples.json`). if i don't get to that part today, i will after break  and can tackle with the documentation (in general) section that you talk about above! 

i'll report back before the end of the day.

thanks again!

**Comment by makella** [comment]
@elenatorro did some testing, but definitely would like to spend more time!

Is it ok with you if I spend more time going through after the break? As discussed, there's a lot (which is great!) so I want to take the time to go through all of it in more detail and discuss some things with you too.

I have been making a notebook to go through the different pieces and cover some of the pains from the [slides](https://docs.google.com/presentation/d/1gq506H4rQzebWlfFz0Xpyt_P38I37pQNnQN5M7yGkC4/edit#slide=id.g6b6a177370_0_0). 

You can see it so far here: 
http://localhost:8888/notebooks/examples/layers/style_api_updates.ipynb

I think it will be good to discuss before updating the examples, etc. too... 

So far, here are my notes/thoughts:

### General
  - I'm confused! I thought that we would still be able to use CARTO VL at the Layer if put inside `''' ... '''`
    - for example, see this notebook: http://localhost:8888/notebooks/examples/real_use_cases/visualize_temperatures.ipynb
  - **I really hope we still can!**

### Style helpers
- In the `basic_style` the `opacity` parameter isn't working
- I think we should still have the legend title labeled with the attribute being mapped by default. Even more so because the default hover popup is labeled:
Screen Shot 2019-12-23 at 2 17 31 PM

- A note to discuss what we think about the title and description assigned to both the legend and widget, in a case like this:
Screen Shot 2019-12-23 at 2 15 30 PM

- i think that we should still have the legend be labeled with the attribute name by default like we did before

- Do you think it will be intuitive for a user to know that the default popup type is hover and in order to turn it off, they have to set `hover_popup=False`?

```
Layer(
    'demographics_sf',
    style=color_continuous_style(
        'masters_percent',
        size=5,
        stroke_color='white', 
        stroke_width=1
    ),
    hover_popup=False,
    widgets=True,
    title="Percent Master's Degree",
    description='by block group',
    footer='Data: US Census',
)
```

### Legends
- its great that we have the option to use different legend types, but is it still possible to use legend subtypes? For example, for a continuous color point map, can I still access other legend types like `color_continuous_polygon`? this is another pattern that we've been seeing in the DS maps and one that I've used myself, for example:
Screen Shot 2019-12-23 at 1 36 55 PM


### Other/Notes
- the `title, description and footer` parameters seem out of place to me when not inside of a class... i also understand why they aren't best in the `style` class but wondering if there is an alternative option for us to explore. For example, them being outside in a case like this seems out of place... what do you think?
```
Layer(
    'global_power_plants',
    style=color_category_style(
        'fuel_type',
        size=5,
        stroke_color='white', 
        stroke_width=1
    ),
    title='Global Power Plants',
    description='Power plant locations around the world',
    footer='Source: World Resources Institute',
    widgets=[
        formula_widget(
            'count',
            title='Number of Power Plants',
            description='Zoom, pan or filter to update count'
        ),
        category_widget(
            'country',
            title='Country' 
        ),
        category_widget(
            'fuel_type',
            title='Fuel Type'
        )
    ] 
)
```
- should we have the ability to `reverse` the color ramp?

**Comment by elenatorro** [comment]
Hi @makella, thanks for the review! I'm leaving my thoughts here:

* **CARTO VL style syntax**:

    - The idea was to avoid using the string style, we could have it back but only for testing purposes and internal usage

* **opacity in basic_style** 
    * to be fixed

* **legend default title**
    - to be fixed

* **legend and widget title, description and footer attributes when defined in the layer:**
    - I think that's the expected behaviour and I wouldn't try to over-complicate the logic, is the user's responsibility to change that.

* **`hover_popup=False`**
    - Yes, I'll add this information to the reference

* **legend subtypes:**
    - we didn't discuss anything about this in the research, but if we want to include subtypes we can do it, but maybe it's better to do this using a parameter instead of using a different helper. We can talk about this!
 
* **title, description and footer:**
    - For me they seem ok at the Layer level instead of inside the style, cause actually they're not a 'style' property, and I think they "describe" the Layer. If we don't like it, we can always use it as legend / widget parameter and remove them from the Layer.

* **reverse palette:**
    - yes, we should add it, but we need to think about the syntax

**Comment by Jesus89** [comment]
Great research @makella! and great responses @elenatorro. I agree with all of them. Just want to point some of them:

The goal of having "title", "description", and "footer" param at the Layer level is to provide some defaults for both default legend and default widget. However, the user is going probably to customize this on 99% of the time, so have different titles for the legend, widget, popup, etc. Also, it seems that it doesn't fit pretty well.

So my proposal is to simplify the logic: use the name of the attribute as the title for the default UI components: popups, legends, widgets. Then, if the user wants to customize any content it must use the helpers.

```py
# This shows the default UI components using `demographics_sf` as title, it's just a quick check of the components.
Layer(
    'demographics_sf',
    style=color_continuous_style(
        'masters_percent',
        size=5,
        stroke_color='white', 
        stroke_width=1
    ),
    legends=True,
    hover_popup=True,
    widgets=True
)
```

```py
# This shows the custom UI components for the final map
Layer(
    'demographics_sf',
    style=color_continuous_style(
        'masters_percent',
        size=5,
        stroke_color='white', 
        stroke_width=1
    ),
    legends=color_continuous_legend(title='Mimimi'),
    widgets=histogram_widget(title='Momomo'),
)
```

**Comment by elenatorro** [comment]
I thought the same, **but** just take into account that it won't be possible to do something like:

```py
Layer( 'global_power_plants',
   style=basic_style(color='blue'),
   title='Global Power Plants'
)
```

And you'd have to create a basic legend:

```py
Layer('global_power_plants',
    style=basic_style(color='blue'),
    legend=basic_legend(title='Global Power Plants'
)
```

**Comment by elenatorro** [comment]
ToDo:

This PR:

- remove title, description and footer by default in the Layer level
- legend default title: value label
- add style string for testing purposes
- fix opacity in basic style
- hover_popup=False in the reference

Next:
- Legend subtypes
- Reverse palette

**Comment by makella** [comment]
@elenatorro @Jesus89 I just realized that the `title`, `description` and `footer` parameters were removed from the Layer level. Can we talk a little bit about this and follow-up with @elenatorro comment: https://github.com/CartoDB/cartoframes/pull/1403#issuecomment-568698867

Since we offer a legend and popup by default with any style, I feel like it is counterintuitive and complex to have to go so far as a user to change these titles. 

My original comment was about it feeling strange at the Layer level but is it something we can put inside the style? Again, since a style packages a Legend, Popup and the option for a Widget, I really feel like we need to give more access to these parameters like we used to have in the style helpers.

for example, could we go back to this pattern?

```
Map(
    Layer(
        'commercial_burglary_2',
        color_category_style(
            'day_of_week',
            size=10,
            stroke_width=1,
            stroke_color='blue',
            opacity=0.5,
            title='Day of the Week',
            description='description',
            footer='footer'
        )
    )
) 
```
Right now a user would have to go this path _just_ to change the title elements:

```
from cartoframes.viz import color_category_style, color_category_legend, popup_element

Map(
    Layer(
        'commercial_burglary_2',
        color_category_style(
            'day_of_week',
            size=10,
            stroke_width=1,
            stroke_color='blue',
            opacity=0.5
        ),
        legends=color_category_legend(title='Day of Week'),
        hover_popup=[popup_element('day_of_week', title='Day of Week')]
    )
)  
```
@Jesus89 while I agree that users will want finer customization, I really think that since we are providing components by default that we should also provide options to modify things like the titles.

My original comment was that it felt weird to be in the Layer but

**Comment by cmongut** [comment]
Hi Mamata! Yeap, we discover this need testing the new API with data scientists --> #1430

**Pull request merged**
