### PR TITLE
Allow showing map info

### PR DESCRIPTION
**Pull request by elenatorro**
Related issue https://github.com/CartoDB/cartoframes/issues/631

Add zoom and center map information if show_info is set to True in the map

Screenshot 2019-05-27 at 08 50 49

### CODE REVIEW

**Comment by Jesus89** [comment]
I would add this new parameter `show_info` to the Map docs

**Comment by andy-esch** [comment]
Can we change the format so that it is copy and paste-able?

For example, a user can copy the text in the current view and paste the exact text into the Map argument to get that view reproducibly?

**Comment by Jesus89** [comment]
Yes. It would be like `center=[0.0, 0.0], zoom=1.0`, right?

**Comment by andy-esch** [comment]
It looks like this is the way to add zoom and center to the map:
```python
viewport={'zoom': 15, 'lat': 38.8784023, 'lng': -77.1169879}
```

**Comment by elenatorro** [comment]
updated!

**Comment by andy-esch** [comment]
Thanks @elenatorro ! ❤️

**Pull request merged**
