### PR TITLE
Experimental cached geocoding for dataframes

### PR DESCRIPTION
**Pull request by jgoizueta**
This uses a table as a geocoding cache for a dataframe.

The intention is to prevent unnecessary geocoding for _reproducible_ (e.g. notebooks) code. For example:

```python
gc = Geocoding(credentials)
df = pandas.read_csv('my_data')
df = gc.cached_geocode(df, 'address', table_name='my_data').data
```

If we execute this repeteadly it will only actually spend geocoding credits the first time, even though we take the data every time from some external file. If the file eventually changes only credits for new addresses will be used up.

cc @cmongut

### CODE REVIEW

**Comment by jgoizueta** [comment]
Note: for context, the workaround for these cases, as [advised in the docs](https://github.com/CartoDB/cartoframes/blob/f1a53aaecf3bfed34e590df9308c91aa5a07f3f3/docs/includes/data_services_geocode.rst#saving-quota) is to save elsewhere the geocoding results when not using persisted tables:

```python
dataframe = pandas.read_csv('my_data')
dataframe = Geocode().geocode(dataframe, 'address').data
dataframe.to_csv('my_data')
```

**Comment by jgoizueta** [comment]
Should we make this the default behaviour for `geocode()` with a DataFrame input and a `table_name` parameter?

In that case, should we also provide the original behaviour also? i.e. providing a Dataframe and saving as a table but not taking hashes/geoms from the existing table.

One problem to make this the default is that we have `if_exists='fail'` by default, and I think we should keep that default for consistency with other `if_exists` uses. For our new cache behaviour the `if_exists` value ought to be `replace`. We could make just `geocode(dataframe, table_name=..., if_exists='replace')` equivalent to `cached_geocode` and drop support for the original behaviour. But I find it a little confusing that if we change the `if_exists` value the behaviour is so different.

Another options is to add and argument to `geocode`, e.g. `cached=True`, or perhaps `cached='table_name'` but the problem I see is that it would only apply to Dataframe inputs and do nothing otherwise. (Well, we could also support the query Dataset case).

So the options I see are:

##  1. Keep a separate method for cached geocoding of dataframes

That is, `cached_geocode` or other name

## 2. Use the general method

### 2.1. Use dataframe with table_name and if_exists=replace case

So we change the behaviour of `gc.geocode(dataframe, table_name='...', if_exists='replace')` to that of `cached_geocode``

Problem: removing `if_exists` or using 'append' or 'fail' would change behaviour

### 2.2. Use new parameter

```python
gc.geocode(dataframe, cached='table_name')
```

This new parameter is incompatible with `table_name`/`if_exists` and requires a dataframe (but we could relax the latter).

:duck: After writing this I like 2.2

**Comment by cmongut** [comment]
This is awesome @jgoizueta. Let's talk about it tomorrow after discussing it with Agi.

**Comment by Jesus89** [comment]
Hi @cmongut. How is this going? Do we have the agi/jatorre approve to merge this?

**Comment by cmongut** [comment]
We don't a confirmation yet, I'll ping Agi today

**Comment by Jesus89** [comment]
I fixed the docs. I also have found an issue, because `_cached_geocode` uses `self.columns` but this is set after the call. I'll fix it.

**Pull request merged**
