### PR TITLE
Use datetime64[ns] (Python) <--> date (PSQL)

### PR DESCRIPTION
**Pull request by dmed256**

### CODE REVIEW

**Comment by andy-esch** [comment]
It turns out that this isn't such an easy fix unfortunately. @michellemho noticed it and opened a ticket here: https://github.com/CartoDB/cartoframes/issues/66 I'd be interested in your perspective on this. I could see adding a force coerce for datetimes arg to `cc.read`, but think that allowing the user to use pandas tools to do that instead would be more powerful.

**Comment by michellemho** [comment]
Also see discussion in https://github.com/CartoDB/cartoframes/pull/100. The problem is how to convert invalid or out of bounds datetimes.

**Comment by andy-esch** [comment]
In summary, this PR refactors the schema enforcement that a DataFrame gets from a postgres table. It relies on pandas DataFrame constructor to properly infer the types for all cases except timestamps. In that case, it tries to update the type to `datetime64[ns]`. If that fails, it keeps it as a string.

This also changes the output from `None` to an empty DataFrame.

**Comment by andy-esch** [comment]
I added some tests on schemas from pg -> dataframe to ensure things are turning out as expected. They pass on my machine, so I'll merge this in shortly.

**Pull request merged**
