### PR TITLE
adds html repr to layer

### PR DESCRIPTION
**Pull request by andy-esch**
The goal of this is to make `Layer` easier to use / more accessible. While the Layer will behave the same way within `Map`, this just adds the `_repr_html_` so that within Jupyter, we get a preview of the layer.
Screen Shot 2019-07-16 at 1 24 14 PM

~~I'm concerned about this being a circular dependency because Map requires Layer, and `Layer()._repr_html_()` requires Map.~~ -> _Not the case. While Map uses layer properties, it doesn't require/import `Layer`._

Besides this, it'd be nice to have a string representation, but that depends on other things, like `Source` and `Dataset` having string representations too, so that should wait for another PR.

### CODE REVIEW

**Comment by elenatorro** [comment]
Nice! I find it useful for quick single-layer visualizations, and this will work then with layer helper methods ✨ About the circular dependency, I'm not 100% sure (cause I'm pretty new to Python) but we're not using the Layer class in the Map.

Also, if we decide to include this, take into account we need to add it to the documentation.

**Comment by Jesus89** [comment]
Cool!

**Comment by andy-esch** [comment]
Yeah, looking deeper it doesn't look like it will be a circular dependency :) @elenatorro, @Jesus89 can you explicitly approve (or deny ;))?

**Comment by Jesus89** [comment]
This is awesome for the helper methods :sparkles:

**Comment by andy-esch** [comment]
Docs updated!

**Pull request merged**
