### PR TITLE
Fix iframes in examples for dev-center

### PR DESCRIPTION
**Pull request by VictorVelarde**
Fixes iframes inside the examples (markdown), that appear broken at Developer Center
> kramdown, used in Jekyll blows up if not using "" around iframe attributes, like height and width

### CODE REVIEW

**Comment by andy-esch** [comment]
@VictorVelarde, anything you need me to do here?

**Comment by VictorVelarde** [comment]
Hi, @andy-esch I'm on it. I'm currently changing the width to 100%. I'll push and make a new dev-center deployment.

After that I'll probably ask for your help, as we have still a pair of 'white iframes' (probably an internal parsing problem with their content)

**Comment by VictorVelarde** [comment]
Hi @andy-esch 
These last changes improve the style of the iframes.

What I have found is that the 'white iframes' (displayed in http://cartoframes-examples-updates.developers.carto-staging.com/developers/cartoframes/examples/#example-example-datasets) have an **empty script tag inside the code**, in the ExampleDatasets.md file, so I guess you should have a look at them, to recover those pieces of code or maybe removing some of them.

**Comment by andy-esch** [comment]
💥 Amazing work @VictorVelarde

Yeah, looks like the script was removed somehow. If you're done here, I'll make a commit to add it on this PR.

**Comment by andy-esch** [comment]
Ok those last two maps are fixed:
http://cartoframes-examples-updates.developers.carto-staging.com/developers/cartoframes/examples/#example-example-datasets

**Comment by andy-esch** [comment]
There's a weird effect:
When you first look at the page, none of the interactive maps are zoomed correctly, but if you reload the page the auto-zoom/centering takes effect and the maps are zoomed/centered correctly.

But I consider this good to go. @VictorVelarde, I'm happy to take care of all the merging of the branches, etc. if you're comfortable with the dev center branch and this one.

**Comment by VictorVelarde** [comment]
Sorry for the delay @andy-esch. Yes! feel free to merge this work.

I'm gonna create another issue for the 'auto-zoom' / reload thing, and I will try to have a look at it today or tomorrow, but we can tackle that detail in another PR, so 🚀

**Comment by andy-esch** [comment]
I found one more script tag that had errorneous code 🤷‍♂️ . I'll let the docs rebuild to make sure all looks ok, then I'll start the merging process between this branch and dev center.

**Comment by andy-esch** [comment]
Strange test run where `matplotlib` was installed in some of the envs even if not requested. But all's good so merging, loss of coverage should be temporary.

**Pull request merged**
