### PR TITLE
Documentation updates for consolidation

### PR DESCRIPTION
**Pull request by andy-esch**
## ToDos
- [ ] #410 Example notebooks population examples section
- [x] #409 Sphinx docs in reference
- [x] #408 Spatial Analysis Guide
  * McDonald's Dataset: 
- [x] #407 Data Observatory Guide
- [x] #406 Quick Start Guide
- [x] #405 Cartography Guide

### CODE REVIEW

**Comment by csubira** [comment]
Hi @andy-esch , I'm working on this issue https://github.com/CartoDB/developers/issues/537 trying to merge all the `documentation` branches to their repository default branches in order to make easier to developers to update the doc. 
I know that we are still trying to find a solution for the sphinx -> developer center format convert issue https://github.com/CartoDB/developers/issues/489. However, considering that in involves a conversation and development and it's going to take longer to solve, how do you see reviewing/updating this documentation (the one published in dev center) maybe store it under a `developer-center` folder to be isolated from the _readthedocs_ build/deploy and merge it to master to have it updated in the site?

**Comment by andy-esch** [comment]
Hey @csubira! Merging to master sounds good to me.

What I was thinking of doing for the near-term is to have all content (guides, examples) on dev center and on the `reference` page just link to the https://cartoframes.readthedocs.io/en/stable/ page. This way we always get up-to-date documentation and it's a single source. In the middle term we can find a solution on a better integration. Doing it this way, to me, makes it a much less confusing experience for users of the dev center.

What do you think? If we do it this way, the reference will something like this only:
```md
## cartoframes documentation
CARTOframes documentation is currently hosted on ReadTheDocs:
https://cartoframes.readthedocs.io/en/stable/
```

**Comment by csubira** [comment]
Sounds ok to me! Where do you want to place the folder with the guides and examples of the dev center? Right on the source (at the same level of `docs`)? Should I rename it to `developer-center`?

**Comment by andy-esch** [comment]
For now I'd like to keep `docs/` as it is if possible. Could the `developer-center/` folder be inside `docs/`?

**Comment by csubira** [comment]
Yes, `developer-center` inside `docs/` sounds perfect. Would it be a problem to build the doc for readthedocs?

**Comment by andy-esch** [comment]
We can make it work still but it might take a bit of back and forth to make sure everything is structured correctly.

The steps I see (please correct if I'm wrong or missing something):
1. merge master into this branch
2. ensure that readthedocs compiles correctly
3. ensure that dev center compiles correctly
4. get rid of things that aren't needed (there are some experiments in this branch that we should delete)

**Comment by csubira** [comment]
Yes, that's correct, the steps are really well defined! I've tried to edit it to make it the first attempt but I don't have access rights to commit. So, I understand that I should wait for you to do it and then test if the connexion works with the dev center fetching system, does it sound ok?

**Comment by andy-esch** [comment]
Just added you as a collaborator! I'm happy to jump in on any part of this, especially the readthedocs. Let me know.

**Comment by csubira** [comment]
I've completed steps **1** (merge master into this branch) and **3** (ensure that dev center compiles correctly) and it's showing properly -> this is the staging link to check it: http://537-update-default-branches.developers.carto-staging.com/developers/cartoframes/ 

As agreed before, there's a new folder (`developer-center`) inside `docs` with guides, support, examples and the new reference page (markdown with text pointing to readthedocs stable)
I've kept the old reference markdowns in a folder called `_internal` that is not copied to be published in dev center, but I did not want to delete that info without knowing if you wanted to keep it or we're using it in the future. 

Now, if that's ok I'll pass the ball to you @andy-esch to check step 2. 
Let me know if you want to change anything regarding the folder structure.

**Comment by andy-esch** [comment]
super, thanks @csubira :) I'll get started on the readthedocs piece today. 

On cleaning things up, is it correct that everything under `/docs/reference` is not needed? It's not used in readthedocs.

**Comment by csubira** [comment]
If it's not used in readthedocs you can remove it. The part used in Dev center is already inside its folder.

**Comment by andy-esch** [comment]
Ok @csubira, all looks good now :) 

Is there a way to configure the version in readthedocs from this repo? That is, I'd like to update the v0.6.0 to v0.9.2 somehow from this repo. The version is in `cartoframes/__version__.py`.

**Comment by ivanmalagon** [comment]
Hi!

CARTOframes docs are broken in https://carto.com/developers/cartoframes/ so deleting/moving things  around hasn't been harmless.

I'm going to point the documentation build to the new `developer-center` folder and check locally if at least we can show something in the website.

Apart from that, speaking about your suggestion, @andy-esch , about having the reference tab linked to `readthedocs`, I'm summoning @alonsogarciapablo , now the sovereign product manager of the dev center. One of the goals of the dev center was to have a similar look & feel in all docs and this approach diverges from that.

**Comment by andy-esch** [comment]
Hey @ivanmalagon, 100% agree that having the same look and feel is the goal. This is just a temporary fix to the docs to make sure we have one source that is always up to date. This is just one of many steps forward to achieve the goal you suggest. After we get this in place, we're going to start working on the guides, examples, etc.

We need a plan for getting the reference section into the dev center, but so far that's been elusive given the difficult of getting sphinx documentation into markdown files.

**Comment by alonsogarciapablo** [comment]
I talked to @csubira about this yesterday. It's very important to provide an updated documentation so it's okay linking to readthedocs for now.

**Pull request merged**
