### PR TITLE
allows use of overwrite + privacy in write operations

### LINKED ISSUE #252: with overwrite and privacy flags set in cc.write, privacy is not updated
This is due to:
1. Import API does not replace dataset, so `dataset_1` is created
2. Once fully imported, cartoframes renames `dataset_2` with the SQL API
3. Since it's via SQL, the CARTO metadata is not updated since that's done with the `api/v1/table` or `api/v1/viz` endpoint. This effectively means that the old table is replaced by the new one, but the metadata for the old one is kept while the new one's is removed.

The way around this is to use the `api/v1/table` endpoint if possible.

### PR DESCRIPTION
**Pull request by andy-esch**
closes #252

### CODE REVIEW

**Comment by Eh2406** [comment]
I doubt this closes #252. I think that reloading the web ui, will reset the table to private.

My current code uses an explicit  
```python
dataset = dataset_manager.get("table_name")
dataset.privacy = u'LINK'
dataset.save()
```
And still when the web ui is reloaded it is private. 

If there is an easy way for me to install a version with this merged I will test.

**Comment by andy-esch** [comment]
Ok, it's in the tests and seems to work as expected, but I'd love if you could verify.

You can install from master with this:
```bash
pip install git+https://github.com/cartodb/cartoframes.git#egg=cartoframes
```

**Comment by Eh2406** [comment]
I am not surprised your test pass, I have always been able to set the privacy of the updated table. It just gets reset to `private` when the ui is reloaded.

I will test now.

**Comment by andy-esch** [comment]
Good to know -- I'll look into that

**Comment by Eh2406** [comment]
I stand corrected. The new code seems to be working! Thank you!

**Comment by andy-esch** [comment]
Great!! Thanks!

**Pull request merged**
