### PR TITLE
josema/ch79550/add_category_widget

### PR DESCRIPTION
**Pull request by josemazo**
Story: https://app.clubhouse.io/cartoteam/story/79550/add-categorywidget

### CODE REVIEW

**Comment by josemazo** [comment]
> Code LGTM, but during the acceptance, I found an issue. I have tested `read_only=False` with the first example, and it seems that selecting a category does not work.
I've tested multiple times and `read_only=False` & `read_only=True` work like expected with WebSDK and CARTO VL :cry:

**Comment by Jesus89** [comment]
OK, after checking this, the no-data issue was related to the random zoom changing in the map, so data was out of the viewport. The only point is a regression after rendering a list of category widgets with VL.

**Comment by josemazo** [comment]
Re-review time!
The problem was that in that example, we are reusing the layer between two maps with different rendered, so the error was there even before. A little fix in the last commit.

**Comment by Jesus89** [comment]
OK. It makes sense. However, there is a test failing (I think there is a random test regarding the order in an array, so feel free to skip it.

**Comment by josemazo** [comment]
No, we need to fix it!

**Comment by Jesus89** [comment]
I remember changing this test at least 3 times, because of the order. Let me know when it's fixed (to avoid failing again in the future randomly)

**Comment by josemazo** [comment]
Fixed! The thing is at some point in the PopupList the order is reversed, and if the Layer is used again, the order is going to be reversed one more time. So it needs to be restored after it's used.

**Pull request merged**
