### PR TITLE
Added requirements-docs.txt

### PR DESCRIPTION
**Pull request by antoniocarlon**
Added `requirements-docs.txt` for documentation generation

Related to https://github.com/CartoDB/cartoframes/pull/397

### CODE REVIEW

**Comment by andy-esch** [comment]
Looks good. We should probably update requirements.txt by removing Sphinx, napoleon, too. Would you mind doing that (and adding appdirs to it)?

**Comment by antoniocarlon** [comment]
Done! :)

**Comment by andy-esch** [comment]
I'm seeing an error building the readthedocs version of the docs.

```
error: python-dateutil 2.7.0 is installed but python-dateutil==2.5.3 is required by set(['pyrestcli'])
```

It looks like it's a conflict with pandas, which wants `python-dateutil>=2.0`. I forked @danicarrion's pyrestcli and PR'd to solve this, but not sure if tests will pass.

We can update the `requirements-doc.txt` with this instead of pyrestcli:
```
git+https://github.com/andy-esch/pyrestcli@update-dateutils-version#egg=pyrestcli
```

**Comment by andy-esch** [comment]
Ok, since https://github.com/danicarrion/pyrestcli/pull/21 was merged [pyrestcli v0.6.5 was released](https://pypi.python.org/pypi/pyrestcli). So we should probably update all references to that, including the setup.py. And I'll do a new release of cartoframes to avoid possible conflicts. Looks like python-dateutils was updated two days ago.

**Comment by andy-esch** [comment]
It now works as expected on readthedocs after the dependency fix on `pyrestcli`. For the record, this also requires a change on readthedocs to use `requirements-docs.txt` Through Admin -> Advanced Settings. I'll update that once this PR is merged.

**Comment by stuartlynn** [comment]
IS this good to merge? We want to get going with producing the rest of the documentation for carto frames so it would be good to get this merged in. It looks fine to me

**Comment by antoniocarlon** [comment]
I have tested the generated documentation and looks OK to me. It can be merged if @andy-esch agrees

**Comment by andy-esch** [comment]
Great, I'll update this with master and merge in once the tests pass. Thanks @antoniocarlon :)

**Pull request merged**
