### PR TITLE
Fix Enrichment API methods

### PR DESCRIPTION
**Pull request by elenatorro**
This PR aims to solve https://github.com/CartoDB/cartoframes/issues/1137

**Current issues:**
- [x] Fix table namespace for filters (right now, filter name could be ambiguous)
- [x] ~Problem when enriching points from a **public** dataset (check `data_enrichment/points_enrichment_public_dataset` examples to reproduce it). It generates different values for each point~ related with DO

### CODE REVIEW

**Comment by arredond** [comment]
Congrats for the PR @elenatorro ! It looks awesome and certainly much clearer.

One thing I find confusing is how the `agg_operators` part works. When there are no aggregation operators specified it's pretty clear (use the default, if available in the metadata `agg_method` field).

However, I find it weird that the user has to refer to a variable by slug (or ID, I suppose) but then specify the aggregation using the variable's `column_name` as the dictionary key. I think this has several drawbacks:

- I understand we specify variables to enrich (instead of full datasets) to allow enriching with variables from different datasets. But what if the variables have the same `column_name` in their respective datasets? For example, if I were to enrich my geometry with two population columns from different datasets (both called `pop), in order to compare them...

- If I already know the slug (which uniquely identifies a variable), why not just use that for the `agg_operators` dict, too? Of course, that would imply looking up the proper column ID in the metadata (but we're already doing that).

- It'd be nice to be able to specify several aggregation functions for a single variable ([just like Pandas does](https://pandas.pydata.org/pandas-docs/version/0.23/generated/pandas.core.groupby.DataFrameGroupBy.agg.html)). In this case, we'd have to differentiate them somehow (maybe adding a `{func}_` prefix?)

**Comment by oleurud** [comment]
Ei @arredond I think your thoughts make sense. I am going to create them in new issues in order to tackle them, allowing to merge this one

**Comment by elenatorro** [comment]
Thanks for the review! I also agree that @arredond comments about aggregation functions make totally sense, and it'd be great as @oleurud says to address them in a different issue separately.

**Comment by oleurud** [comment]
The issue: https://github.com/CartoDB/cartoframes/issues/1174

**Pull request merged**
