### PR TITLE
Columns in enrichment with aggregation none

### PR DESCRIPTION
**Pull request by oleurud**
Solves https://github.com/CartoDB/cartoframes/issues/1295

In addition to the issue, I have removed some duplicated stuff in polygons enrichment tests

### CODE REVIEW

**Comment by oleurud** [comment]
@arredond I have added you here to validate the result when the CR will be ready. If you want, we can do it together

**Comment by Jesus89** [comment]
I miss some docs about how to use the aggregation none

**Comment by oleurud** [comment]
No one of these are valid options.

> NOK: aggregation='NONE'. This should be supported since it is 'SUM', 'AVG', etc.
NOK: aggregation=None. Value None is included to compute the aggregation_method, but it fails when the query is built.

To work without aggregation, the value is `Enrichment.AGGREGATION_NONE`

> NOK: aggregation={variable.id: 'none'}
NOK: aggregation={variable.id: 'NONE'}
NOK: aggregation={variable.id: None}

These make no sense. We can not aggregate one and not the other.

**Comment by oleurud** [comment]
About the documentation, we have:
- as general explanation of enrichment https://github.com/CartoDB/cartoframes/blob/25a62dcfe3ba49023318102e8b6c5a40164db18b/cartoframes/data/observatory/enrichment/enrichment.py#L133-L142
- About aggregation https://github.com/CartoDB/cartoframes/blob/25a62dcfe3ba49023318102e8b6c5a40164db18b/cartoframes/data/observatory/enrichment/enrichment.py#L154-L175 

Are you missing anything more?

**Comment by Jesus89** [comment]
> No one of these are valid options: 'NONE', None

I supposed that None was a valid value because of this line: https://github.com/CartoDB/cartoframes/blob/develop/cartoframes/data/observatory/enrichment/enrichment_service.py#L403.

IMO if we are using uppercase strings for the valid aggregations ('SUM', 'MIN', 'MAX, ...), instead of constants, we must use also uppercase string for 'NONE'. I think users are going to expect this behavior.

I think it would be also nice to validate this parameter because if you pass a wrong value, the error is not very useful:

```
[{'reason': 'invalidQuery', 'location': 'query', 'message': 'Function not found: none at [3:13]'}]
```

> Are you missing anything more?

I would add an example using aggregation none.

Since I'm not an enrichment expert user, it would be nice to listen also to @arredond and @andy-esch.

**Comment by oleurud** [comment]
We are not saying use `none`, `None` or `NONE`, it is an internal label. We are saying use `Enrichment.AGGREGATION_NONE`. I used a constant instead of a string to avoid confusion/collisions with BigQuery stuff. I did not use `None` because we also have `Enrichment.AGGREGATION_DEFAULT` case and I would like to solve both cases in a similar way.

About the function names, we do not control that. Ideally, If Google adds more functions (remove or change one), we should support them. But it is my opinion.

**Comment by oleurud** [comment]
Also, @arredond and I did a detailed acceptance checking the results of the query and :green_apple:  

About the constant vs string thing, we have created a different issue to check opinions there. Alvaro also prefer the string option.

**Comment by arredond** [comment]
`'default'` + `None` looks good to me!

**Pull request merged**
