### PR TITLE
Feature/describe

### PR DESCRIPTION
**Pull request by alejandrohall**
Related to #977

### CODE REVIEW

**Comment by oleurud** [comment]
The code looks good. The tests are failing, take a look. And also, it would be nice having tests, at least for the methods in summary module

**Comment by alejandrohall** [comment]
@oleurud Tests already working!

**Comment by Jesus89** [comment]
Hi @alejandrohall. Could you add a list of the implemented features to do a complete acceptance? Thanks!

**Comment by alejandrohall** [comment]
@Jesus89 done!

**Pull request merged**
