### PR TITLE
Default schema

### PR DESCRIPTION
**Pull request by oleurud**
Fix https://github.com/CartoDB/cartoframes/issues/707

### CODE REVIEW

**Comment by oleurud** [comment]
Not an objective of this fix: I had not paid attention to:
```
from .auth import _default_context
```
I don't like it, it should a method from a not a dynamic import (maybe  `default_context` should be a singleton class with a getter)

**Comment by oleurud** [comment]
Sorry, I have added you as reviewers to soon

**Comment by Jesus89** [comment]
https://github.com/CartoDB/cartoframes/pull/709

**Comment by andy-esch** [comment]
💪

**Pull request merged**
