### PR TITLE
Positron set to default, helpers and examples adjusted

### PR DESCRIPTION
**Pull request by makella**
Related to: https://github.com/CartoDB/cartoframes/issues/758

### CODE REVIEW

**Comment by makella** [comment]
This PR:
- [x] Sets positron to the default basemap
- [x] Removes `reverse()` for continuous and bins color schemes
- [x] Adjustments to helper methods part 1 / part 2 and set viewport and basemap examples to account for the basemap change

cc @Jesus89

**Comment by Jesus89** [comment]
Btw, @makella if you change the default style, the tests should be also updated: https://github.com/CartoDB/cartoframes/blob/develop/test/viz/test_style.py.

Let me know if you want to update the default style.

**Comment by elenatorro** [comment]
I'm going to change the tests in the current branch where I'm updating the examples, thanks @Jesus89 & @makella!!

**Comment by makella** [comment]
@Jesus89 i see i didn't understand the error but thanks for clarifying!! yes, i do want to change some of the defaults. let me try to do the line opacity one in another test branch to see if i can get the workflow.

**Pull request merged**
