### PR TITLE
Remove unused BigQueryClient and related tests

### PR DESCRIPTION
**Pull request by dgaubert**

### CODE REVIEW

**Comment by dgaubert** [comment]
Apparently, we do have clients using this class, let's stand by this PR until we have a clearer view how to deprecate this class

**Comment by cmongut** [comment]
Yeap, some customers wanted to visualise their DO datasets and we gave them a workaround that uses this private client. We hope we can get rid of it soon.

**Comment by Jesus89** [comment]
Hi, I have added the `do-not-merge` tag until we release the v1.0.2. Then, I'll remove it :)

**Comment by Jesus89** [comment]
OK, branch release/1.0.2. Removing the tag

**Comment by Jesus89** [comment]
We need to provide a way to get the BigQuery credentials in the API. So blocking this until we have that feature.

**Review by Jesus89 — APPROVED** [review]
The time has come :fire:

**Pull request merged**
