### PR TITLE
Add logger

### PR DESCRIPTION
**Pull request by Jesus89**
Closes https://github.com/CartoDB/cartoframes/issues/422.

- Replace prints by log.x
- Add log_debug() and log_info() functions to set the log level  

NOTE: this is the output of the logger, we can customize the message:
```
2019-12-10 09:49:27,922 - INFO - Success! Data uploaded correctly
```

@cmongut do you think we need to change this (remove time, log level, etc)?

### CODE REVIEW

**Comment by Jesus89** [comment]
Using the `log_debug()` and `log_info()` methods. I thought this is for internal use. Do you think we should expose and document it for all the users?

**Comment by alrocar** [comment]
Sorry I meant a different thing.

Loggers allow to set the log level, so at runtime you decide if you want more verbose logs or not.

For example, now is set to INFO so I assume debug logs are not shown by default. As a user of CARTOframes how can I see the debug logs  or only warnings and errors or in other words how can I set the log level?

**Comment by Jesus89** [comment]
Yes, that's the goal of those functions :). We might improve the naming: `set_log_level('debug')`, `set_log_level('info')`, etc.

**Comment by alrocar** [comment]
sorry I misread them 🤦‍♂ the name change would help, thanks!

**Comment by alrocar** [comment]
Acceptance 🍏 

@Jesus89 not sure if you want to include the requested changes by @oleurud in this PR or in a different one.

**Comment by oleurud** [comment]
Forget it. You could access to it by:
```
from cartoframes.core.logger import log 
```

I confused myself due to the function `init_logger()`, but it is called in the same module

**Comment by alrocar** [comment]
Cool, let's use this as much as possible :)

**Pull request merged**
