### PR TITLE
Adds finer timestamp granularity

### PR DESCRIPTION
**Pull request by dmed256**
The current pgtype `date` chops off hours, minutes, and seconds

### CODE REVIEW

**Comment by andy-esch** [comment]
Great find, thanks! I'm going to merge this into a 'develop' branch soon so the tests can have access to the api key env variable on travis for the testing account, and will merge into master from there.

**Comment by dmed256** [comment]
@andy-esch Thanks!

**Comment by dmed256** [comment]
It seems Carto simplifies the column type as `date` even if the actual type is different in Postgres

**Comment by dmed256** [comment]
Thanks!

**Pull request merged**
