### PR TITLE
Add Country.categories and Category.geographies properties

### LINKED ISSUE #1038: Catalog by smart classes
Pandas implementation of the catalog doesn't work pretty well because of these two main issues:

- Cannot implement a full extension of the classes without corner cases: https://github.com/CartoDB/cartoframes/issues/1032

- The logic of the classes is delegated to the user and it makes quite complicated when the catalog amount of data increases.

Thus, let's move to an approach where classes are smarter.

At the definition, we're just including the properties that work as methods. The rest of the properties are not defined but must appear with the same name as in the metadata DB.

`[]` Denotes a list that will work as an Entity List (see below)

Methods are replaced by properties. I think it's better for a catalog, i.e., `Catalog.countries` 👍  instead of `Catalog.countries()`  

**EntityList**

1. `get`: It will allow finding by id: `Catalog.countries.get('es')`

2. `to_dataframe`: returns a pandas dataframe of the list. 

### Classes

**Catalog**

Catalog.countries => [Country] #Static 
Catalog.datasets => [Datasets] #Static 
Catalog.categories => [Category] #Static 

**Country**

Country.get(<country_id>) => Country #Static
Country.id => String
Country.categories => [Category] 
Country.datasets => [Dataset]
Country.geographies => [Geography]

**Category**

Category.get(<category_id>) 
Category.id => String
Category.datasets => [Dataset] 
Category.geographies => [Geography] #It returns all the geographies with datasets for this category (country and category), This instance of category must be create with the optional parameter category_id
Category.countries => [Country]

**Dataset**

Dataset.get(<dataset_id>) #Static
Dataset.id => String
Dataset.variables => [Variable]
Dataset.variables_groups => { 'group_1': [Variable], 'group_2': [Variable] } # It removes the concept of Variables Groups!
Dataset.geography => Geography

**Variable**
Variable.get(<variable_id>) #static
Variable.id => String
Variable.dataset => Dataset

**Geography**

Geography.get(<geography_id>) 
Geography.datasets = [Dataset]
Geography.support = String (admin|quadgrid|postalcodes)
Geography.support_level = 1,2,3,4
Geography.country = Country

If Geography class is instantiate by providing category_id, datasets method will return all the datasets filtered by the category provided.

### Usage 

Get all categories of a country

>Country.get('usa').categories

Convert a list to pandas

> Country.get('usa').categories.to_dataframe().head()
> Country.get('usa').geographies.to_dataframe().head()
> Country.get('usa').datasets.to_dataframe().head()

Get all datasets of a category

> Country.get('usa').categories.get('demographics').datasets

Get all datasets of a category

> Category.get('geomgraphics').countries.get('usa').datasets

Get all boundaries with demographics datasets

> Country.get('usa').categories.get('demographics').geographies

Get all demographics datasets for block groups of a country

> Country.get('usa').categories.get('demographics').geographies.get('block_groups').datasets()

cc: @alrocar @cmongut

### PR DESCRIPTION
**Pull request by esloho**
Closes #1038 

I added the missing methods and then I realized we could always use `get_all` for those properties so I did a bit of cleaning in code and tests :sparkles:

### CODE REVIEW

**Comment by alrocar** [comment]
Acceptance 🍊 

I've tested the whole list of methods in the original issue and I found a couple of missing ones. Let me know if we should add them:

- `Category.get('demographics').countries`
- Not sure about this, but properties that are actually a FK are returned as an ID instead of the class instance. Examples (not a comprehensive list I guess). I'd say this is not a big deal and in any case I'd open a separate issue in case we want to support that:
  - `Dataset.get('od_acs_1f614ee8').geography`
  - `Variable.get('poverty_b698f5ff').dataset`
  - `Geography.get('carto-do-public-data.tiger.geography_usa_countyclipped_2015').country`

**Comment by alasarr** [comment]
Hi, it'd be great if get method for CatalogList should work with slug too. 

Dataset.get(<dataset_id>).variables.get(<slug>).

If we do that we can say that at everypart we can find by slug or id.

**Comment by alrocar** [comment]
> We discussed this a couple of weeks ago and decided (at least for the moment) to have all FK properties returning the id (but rename them to geography instead of geography_id in the API). The idea was to have it return the whole objects eventually. Should we address this now?

Sorry, it's just I was running the full acceptance cycle and I wasn't aware we decided that 😊 

> However, if we want to have the first option as well, I'll add it. (I already talked to Aroa last week about the fact that we seem to always have 2 ways of doing things, and it's not good.)

Let's do that validation work with @newLadyAga 

@esloho are you going to address [this](https://github.com/CartoDB/cartoframes/pull/1093#issuecomment-541454889) in this PR or in a different one?

**Comment by alasarr** [comment]
Working!

**Pull request merged**
