### PR TITLE
Avoid double logger in Jupyter

### PR DESCRIPTION
**Pull request by Jesus89**
This PR removed the double log in Jupyter notebooks

### CODE REVIEW

**Comment by oleurud** [comment]
I am not seeing the "double log" in `develop` :thinking:

**Comment by Jesus89** [comment]
It may depend on your Jupyter version. @cmongut has also reported this issue.

With your configuration, this PR works OK?

**Comment by oleurud** [comment]
Yes, it works fine for me

**Comment by Jesus89** [comment]
I'll as @cmongut just to make sure

**Comment by cmongut** [comment]
It works at expected 👍

**Pull request merged**
