### PR TITLE
Support uploading DataFrames with non-ascii texts in Python 2

### LINKED ISSUE #1000: Can't upload non-ascii texts in a DataFrame with Python 2
I know it's painful to mess the code to support the dying Python 2, but I guess we have to.

Dataframes with non-ascii text attributes fail with Python 2

In the internal method `DataFrameDataset._rows()` CSV data is built in strings (`str`) using `'{}'.format(val))` then finally encoded with `csv_row.encode()`.

For Python 3 this is fine: the data accumulated in str (as unicode) then coded into the default encoding (utf-8) as a byte string.

But for Python 2 the accumulated string is encoded (`bytes`) and `'{}'.format(val))` will fail if val is a non-ascii `unicode` object. It will work if `val`s are encoded (as `bytes`),  but then if the content is non-ascii it will fail anyway in `csv_row.encode()`.

### PR DESCRIPTION
**Pull request by jgoizueta**
Closes #1000

The fix I propose here accumulates the csv data in unicode form and encodes it only at the end. 
Attributes for non-ascii test can be passed as unicode or encoded as bytes, so that simple strings `'...'` containing utf-8 characters will work both in Python 2 and 3. Explicit unicode string `u'...'` will also work.

### CODE REVIEW

**Comment by jgoizueta** [comment]
Note: the test I have added fails also for Python 3 because it also checks that you can pass encoded attributes (as bytes string).

**Comment by jgoizueta** [comment]
So, to be clear: as a bonus point, we know support non only (unicode) strings such as `'año'` (`u'año' in Python 2), but also strings that have already been encoded as bytes (using UTF-8) like `'año'.encode('utf-8')` (or just `'año'` in Python 2).

**Comment by alrocar** [comment]
Thanks!

Let's put PR in the `Review` column and unassigned, so anyone can take it for revision.

**Comment by oleurud** [comment]
I would like to merge https://github.com/CartoDB/cartoframes/pull/974 first, to have some test before that. Also, we are going to have some conflicts and it would be easier to solve here than there

**Comment by alrocar** [comment]
Removing the `blocked label` after #974 is merged

**Comment by oleurud** [comment]
## Acceptance ok

**Pull request merged**
